# Archivo FUNDING.yml

# GitHub Sponsors
github: RogerPyDev

# Si valoras estos proyectos y deseas apoyar su desarrollo continuo, considera convertirte en patrocinador. ¡Tu apoyo hace la diferencia! 😊

